### ISSUE TITLE
Compatibility with near-operation-file preset

### ISSUE THREAD

**Issue by awinograd** [Code-Hex/graphql-codegen-typescript-validation-schema#137]
👋 I'm looking at integrating this plugin to our codegen. Currently we use the near-operation-file preset. This plugin appears to be incompatible, generating the full GQL schema's worth of zod objects for each file. Is there any interest in adding support for usage with near-operation-file?

**Comment by Code-Hex** [comment]
@awinograd Thanks for your suggestions!

I've never used the near-operation-file preset. I wanna consider how to support it, So could you help me to provide your minimum configuration (yml and GraphQL schema), what do you expected file contents by generating? 🙏

**Comment by Code-Hex** [comment]
Just to be sure, this config did not fulfill your requirements?

https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema#importfrom

**Comment by awinograd** [comment]
@Code-Hex thanks for your response! The inputFrom option is not helpful for solving this issue unfortunately.

I've created an minimum example repository to illustrate my usage:

https://github.com/awinograd/graphql-codegen-typescript-validation-schema-near-operations-file

The latest commit was created by manually editing the generated files to what I think the expected output should be after the previous commit saved the generated ouput. You can re-run generation with `yarn run gqlcodegen`

**Comment by Code-Hex** [comment]
@awinograd Thanks for your great work!

It's midnight in Japan (JST) right now, so I'll check with it when I wake up in the morning!

**Comment by awinograd** [comment]
@Code-Hex on the contrary, thank you for a cool library! Obviously there's no rush or expectation that you do any of this so please tackle at your interest & convenience and please let me know if there's anything else I can do to help

**Comment by Code-Hex** [comment]
@awinograd I'm sorry to reply too late.

I understand about [near-operations-file](https://github.com/awinograd/graphql-codegen-typescript-validation-schema-near-operations-file). This is preset to generate some code by each GraphQL document.

This plugin (graphql-codegen-typescript-validation-schema) is generating validation schema from [GraphQL schema](https://spec.graphql.org/October2021/#sec-Schema) but not from [GraphQL document](https://spec.graphql.org/October2021/#sec-Document). 

I think near-operations-file preset cannot be used because the target of automatic generation is different.

**Comment by awinograd** [comment]
Thanks for looking into the issue @Code-Hex. Not a problem to create the repository. Best of luck with the project!

**Comment by Code-Hex** [comment]
@awinograd Thank you so much!

**Comment by mmahalwy** [comment]
@Code-Hex thoughts on now supporting this?

**Comment by Code-Hex** [comment]
@mmahalwy Hi!
I'm sorry I forgot about this issue for details. It should be supported. If you find any problems, please open a new issue!
