### ISSUE TITLE
Create zod schemas for operation variables rather than just InputObjectTypes

### ISSUE THREAD

**Issue by awinograd** [Code-Hex/graphql-codegen-typescript-validation-schema#140]
Hi @Code-Hex! This is a distinct issue from #137 but perhaps somewhat related in terms of implementation.

I wonder if it makes sense to add an option to produce zod schemas for the variables object expected by a given gql operation (both queries and mutations).

Here is an example of what I'm thinking. Latest commit is expected behavior and previous commit is current behavior.

https://github.com/awinograd/graphql-codegen-typescript-validation-schema-near-operations-file/tree/operations 

~One other note, I'm currently getting a typescript error on https://github.com/awinograd/graphql-codegen-typescript-validation-schema-near-operations-file/blob/c646273e32e32e9f50116388f4a33d839eb26b6e/src/operations.graphql.generated.ts#L68~

~Type '{ foo?: string; }' is not assignable to type 'RecordInput'.~

~But not 100% sure why~

**Comment by Code-Hex** [comment]
@awinograd Thanks for creating minimum reproduction!

I think you need to add tsconfig.json and enable strict mode in compiler options.

See https://github.com/colinhacks/zod#requirements

**Comment by awinograd** [comment]
@Code-Hex whoops I did miss the tsconfig.json! That resolves the tsc error above. I'll strike through the relevant portions in the OP but the original feature request is still relevant I believe

**Comment by Code-Hex** [comment]
@awinograd Thanks for checking your tsc!
I close this issue seems fine.
