### ISSUE TITLE
Any type with "Query" in its name gets ignored

### ISSUE THREAD

**Issue by ctrlplusb** [Code-Hex/graphql-codegen-typescript-validation-schema#167]
For example;

```graphql
type QueryFruitItem = {
  name: String!
}

type FruitsResponse = {
  items: [QueryFruitItem!]!
}
```

The generated schemas will not contain a `function QueryFruitItemSchema() {`.

Using the `zod` schema config, unaware if the same issue stands for the other output types.

Amazing idea this plugin btw 🤩

**Comment by Code-Hex** [comment]
@ctrlplusb Hi 👋 
Thanks for creating this issue and your PR!

I'm checking the PR.

I'm so happy! Thank you!
> Amazing idea this plugin btw 🤩

I saw your repositories and I'm very surprised at what you have achieved!

**Comment by Code-Hex** [comment]
@ctrlplusb I've published a new version that contains this bug fix.

Thank you so much!

**Comment by ctrlplusb** [comment]
Amazing, thank you!
