### ISSUE TITLE
bug: falsy directive args are dropped

### ISSUE THREAD

**Issue by elijaholmos** [Code-Hex/graphql-codegen-typescript-validation-schema#184]
When supplying a [falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) argument to a custom directive, the argument is omitted from the generated schema.

**Sample GQL:** (with codgen config from https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/blob/main/codegen.yml)
```graphql
input EventArgumentInput {
  name: String! @constraint(minLength: 0)
  value: String! @constraint(startsWith: "foo")
}

directive @constraint(
  minLength: Int
  startsWith: String
) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION
```

**Expected Schema Output:**
```ts
export function EventArgumentInputSchema(): yup.SchemaOf<EventArgumentInput> {
  return yup.object({
    name: yup.string().defined().min(0),
    value: yup.string().defined().matches(/^foo/)
  })
}
```

**Actual Schema Output:**
```ts
export function EventArgumentInputSchema(): yup.SchemaOf<EventArgumentInput> {
  return yup.object({
    name: yup.string().defined().min(), // <-- "Expected 1-2 arguments, but got 0. ts(2554)"
    value: yup.string().defined().matches(/^foo/)
  })
}
```

I intend on submitting a PR to resolve this issue.

**Comment by Code-Hex** [comment]
@elijaholmos Thanks for your PR!
I just published a new version which is contained your fixes.

https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/tree/v0.6.2

Thank you!
