### ISSUE TITLE
Use codegen on non-input types

### ISSUE THREAD

**Issue by willd-i2o** [Code-Hex/graphql-codegen-typescript-validation-schema#20]
It seems that with the current version of the plugin, validation schemas are only generated for graphql `input` types found in the schema. i was wondering if it would be possible to add an option to the plugin to generate validation schemas for graphql `type` as well as `input`?

**Comment by Code-Hex** [comment]
@willd-i2o I'm just curious.
How do you think the usage if available code generation for type too.

**Comment by willd-i2o** [comment]
@Code-Hex 

I use apollo client alongside graphql-codegen
My form state is populated with data from `useQuery`, these queries utilise the `type` objects defined in the schema, so therefore my form state is typed against these `type` objects.
My validation schema has to match the form state, since I'm running the validation schema via the zod resolver for `react-hook-form`.
The `input` types are only used when I'm submitting the form and transforming my form state data into a mutation input type. The `input` types don't match 1-to-1 with the `type` types used in the query, so the codegen producing validation schema's for my `input` types doesn't help me with constructing a validation schema for my form.

**Comment by Code-Hex** [comment]
@willd-i2o Thanks for your explanation.
I want to confirm my understanding is correct. for example, there is a schema.

```graphql
type Human {
  name: String!
  age: Int!
}

input HumanInput {
  name: String!
  age: Int!
}
```

Then you want to validate only for `type Human`. and convert any users who have been inputted `type Human` to `input HumanInput` when submitting to mutation, right?

**Comment by willd-i2o** [comment]
@Code-Hex 

Yeah that sounds about right

**Comment by Code-Hex** [comment]
@willd-i2o Thanks. Don't you use fragment also?
I think this a little bit difficult.

**Comment by willd-i2o** [comment]
@Code-Hex 

I think I could do what I would like to do without the codegen supporting fragments, but not entirely sure.

**Comment by Code-Hex** [comment]
I'm sorry. After due consideration, I did not feel this desperately needed to be addressed. If there are other requests, I will revisit this issue.

**Comment by Code-Hex** [comment]
@willd-i2o I'm sorry.

After due consideration, I did not feel this desperately needed to be addressed. If there are other requests, I will revisit this issue.

**Comment by Brian-McBride** [comment]
I use Zod to validate data from my database and other sources as well. Sure that incoming data _should_ be in the model you expect. Of course, corrupted data or a service that broke their API contract would then cause errors in your app. 

I can write my own Zod schemas, of course. But I have to define my outgoing type anyway in graphQL. 
Let's take this example: 

```graphql
  type User {
    id: ID!
    email: String!
    disabled: Boolean
    createdAt: String
    updatedAt: String
  }

  input NewUser {
    id: ID!
    email: String!
  }

  type Query {
    user(id: ID!): User
  }
```

At some point I am going to assemble that User JSON for my `user()` resolver. Let's say I am fetching the data from something like Firebase Firestore. Well, Firestore give you `any` as the base type. Sure, I can cast it in a few ways - but if I don't actually validate that data - it might not be valid. 

If I can auto-generate zod types from the graphql types, then I can further `pick`, `omit`, `extend`, etc... the zod schema for my DB.
