### ISSUE TITLE
Feature Request: Surface the underlying object

### ISSUE THREAD

**Issue by joshribakoff-sm** [Code-Hex/graphql-codegen-typescript-validation-schema#21]
```tsx
export function UpdateUserRequestSchema(): z.ZodSchema<UpdateUserRequest> {
  return z.object({
    email: z.string().nullish(),
    enabled: z.boolean().nullish(),
    first_name: z.string().nullish(),
    last_name: z.string().nullish(),
    role: RoleSchema.nullish(),
    team_id: z.number().nullish(),
  });
}
```

This cannot be extended, instead my idea is to have an option so it outputs this:

```tsx
const updateUserRequestFields = {
    email: z.string().nullish(),
    enabled: z.boolean().nullish(),
    first_name: z.string().nullish(),
    last_name: z.string().nullish(),
    role: RoleSchema.nullish(),
    team_id: z.number().nullish(),
 }

export function UpdateUserRequestSchema(): z.ZodSchema<UpdateUserRequest> {
  return z.object(updateUserRequestFields);
}
```

I could then import `updateUserRequestFields` and extend it prior to passing it to `z.object()` in the consuming code

```tsx
export function MyCustomSchema(): z.ZodSchema<UpdateUserRequest> {
  const fields = updateUserRequestFields
  fields.email.min(1) // extending the validations :)
  return z.object(fields);
}

```

 It could also optionally append:

```tsx
export function UpdateUserRequestSchema(): z.ZodSchema<UpdateUserRequest> {
  return z.object(updateUserRequestFields);
}
```

**Comment by Code-Hex** [comment]
@joshribakoff-sm Thanks. I think you can do by `extend` method like `UpdateUserRequestSchema().extend({ email: z.string().nullish().email() })` .

see: https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/tree/main/example/zod

**Comment by joshribakoff-sm** [comment]
Interesting, thanks for the heads up! Why not surface this on your main readme? There is no way I would have found this on my own 😆

**Comment by Code-Hex** [comment]
@joshribakoff-sm I have written like

> You can check example directory if you want to see more complex config example or how is generated some files.

> ...And I wrote some tips in there.

**Comment by Code-Hex** [comment]
@joshribakoff-sm thanks for reporting.
I fixed returned type to z.ZodObject at v0.4.0

About documentation, welcome PR.
