### ISSUE TITLE
Request: better docs and DX for the directives

### ISSUE THREAD

**Issue by joshribakoff-sm** [Code-Hex/graphql-codegen-typescript-validation-schema#22]
Really cool library!

I'm getting the sense some of this isn't quite ready for prime time for the general use cases people may expect. For example

This doesn't compile:
```
first_name: [String! @constraint(minLength: 50)]! 
```

Whereas this:
```
first_name: [String!]!  @constraint(minLength: 50)
```

Outputs:

```
first_name: z.array(z.string()).min(50),
```

Also is anything supported besides `min`, and `email`? Your docs reference a huge abstract test file and are pretty terse otherwise.

Perhaps you could label this feature experimental, or better document it?

You're also telling people to add `directives` to their `codegen.yml`, but what if people want to load their directives in a GQL compliant manner. Perhaps you could ship first class GQL schema for your custom directives?

**Comment by Code-Hex** [comment]
Is this one supported in GraphQL syntax? I don't think https://spec.graphql.org/October2021/#sec-Type-System.Directives

`first_name: [String! @constraint(minLength: 50)]!`

> This doesn't compile

Do you have any ideas?

> Also is anything supported besides min, and email? Your docs reference a huge abstract test file and are pretty terse otherwise.

Could you please explain more details?

> Perhaps you could ship first class GQL schema for your custom directives?

**Comment by joshribakoff-sm** [comment]
1 - nope, but I guess it's a limitation of doing this with directives? How can you declare the min length is on the string and not the array with these directives?

2 - Basically my only suggestion is to be up front in the readme if this directives idea is still "experimental" and allow extending validations on the client which I cut a separate feature request for #21  :)

3a - Checkout this [Apollo blog post](https://www.apollographql.com/blog/graphql/directives/eusable-graphql-schema-directives/), there is a way to define the directive in the schema. Other tools need to parse the schema that aren't aware of `codegen.yml`.

3b - Apollo is also showing a way to import the directive definitions via an NPM package and pass it to the GQL runtime, see `Using schema directives` header in the above blog post. I'm not sure if this can be introspected like defining it in the SDL, but seems slightly more streamlined that copy pasting YAML into `codegen.yml` file :)

**Comment by Code-Hex** [comment]
@joshribakoff-sm 

1. If so how do we apply the rule for string in array. I think the idea is just your usecase. Please use `extend` method.

2. This feature is not experimental and You can do by `extend` method as mentioned in #21

3. Probably you forget this library is a plug-in for codegen.

If you have any ideas based on code. Welcome PR.

**Comment by joshribakoff-sm** [comment]
1 - If the directives don't support this use case, it's a bit of a limitation. My suggestion would be to document the limitations, and surface (in the main readme) what the alternatives are (extending client side)

2 - Sorry I don't mean any negative connotations here. The server side directives seem to have some limitations. I am wondering if there are plans to address the limitations, and if not my feedback would be to surface the limitations in the main readme

3 - I'm aware it's a plugin for codegen, but if you use these directives to your schema without defining them [in the schema] it breaks many other tools such as ESlint, in addition the user's GQL server won't boot (since it doesn't know about codegen.yml either). I would suggest to revisit the recommendation to define the directives only in codegen.yml and instead recommend defining the directives in the schema itself. Tangentially, it would be good for ergonomics to import the directives rather than copy paste them.

I would be open to making a PR, but I wanted to start this thread to chat over these things first :)

**Comment by Code-Hex** [comment]
1. PR is welcome
2. PR is welcome 
3. I'm not sure this part. It would be helpful if you could provide a small example in code.

**Comment by Code-Hex** [comment]
No replied. Reopen if required.
