### ISSUE TITLE
zod schema generator does not recognize union types

### ISSUE THREAD

**Issue by alisabzevari** [Code-Hex/graphql-codegen-typescript-validation-schema#236]
It seems like the implementation does not recognize the `union` types when enabling `withObjectType` option.

I get `unhandled scalar name` error.

Seems like we should add a condition to handle unions here:
https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/blob/2a61ef2e07b0c19c52e752a93eeead0c0b95f0b8/src/zod/index.ts#L172

**Comment by Code-Hex** [comment]
@alisabzevari  published as v0.7.0
