### ISSUE TITLE
v0.6.2 Doesn't seem to be correct

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [Code-Hex/graphql-codegen-typescript-validation-schema#246]
My changes for example are not in the zip and the published version also does not have the changes.

**Comment by Code-Hex** [comment]
@sschneider-ihre-pvs I've not published your code yet. I will do it after merged #237

**Comment by Code-Hex** [comment]
@sschneider-ihre-pvs published as v0.7.0
