### ISSUE TITLE
implementation with myzod 

### ISSUE THREAD

**Issue by Parables** [Code-Hex/graphql-codegen-typescript-validation-schema#25]
I really love the plugin so much.....

Please can we have an implementation with myzod.

**Comment by Code-Hex** [comment]
Thanks your feedback.
myzod does not seem to provide the extend API.

https://github.com/davidmdm/myzod/issues/51

yup and zod provide it. So we can modify schema if generated a little bit different. (I announced tips here. https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/tree/main/example/zod)


Isn't this inconvenient?

**Comment by Parables** [comment]
I haven't seen where you use .extend feature for zod and besides, the generated output is there to be modified accordingly.

I don't see why this should be an obstacle for supporting myzod.

Moreover, you can use [.and](https://www.npmjs.com/package/myzod#typeand) or Type.map to transform/modify the schema


```ts
const AttributeInputSchemaWithCUID = AttributeInputSchema().extend({
  key: z.string().cuid(),
})
```
Can be written as:
```ts
const withCUID = myzod.object({   key: z.string()  .withPredicate(CUID.isValid, 'must be a valid CUID')
  .map(value => new CUID(value)),
 });
 
const AttributeInputSchemaWithCUID = AttributeInputSchema().and(withCUID)
```

**Comment by Parables** [comment]
So what do you say, does my PR gets merged or what? 93/93 test passed

**Comment by Code-Hex** [comment]
@Parables Amazing your work! Thanks a lot.
And I appreciate your answer about how to extend in myzod also.

I need a little bit fix documents for myzod. but I can handle for it. Great job!

**Comment by Code-Hex** [comment]
Your code is broken on a few points. I need to fix them,

**Comment by Parables** [comment]
I am really grateful for accepting my PR. 

> Your code is broken on a few points. I need to fix them,

Please let me know what I have to do and I will do it ASAP

**Comment by Code-Hex** [comment]
@charlypoly Already fixed it in here https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/pull/28

So no problem!

**Comment by Code-Hex** [comment]
@Parables I fixed the problem in here https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/pull/28

So no problem for now (in v0.5.0)

**Comment by Code-Hex** [comment]
@Parables Sorry again. One more!

Could you fix to be valid syntax of your suggested sample code in your comment? 🙏 

https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/issues/25#issuecomment-1086532098

**Comment by Parables** [comment]
```ts
import cuid from "cuid";
import myzod, { Infer } from "myzod";
import isEmail from "validator/es/lib/isEmail";
import isStrongPassword from "validator/es/lib/isStrongPassword";

const ProfileInputSchema = myzod
  .object({
    username: myzod.string().min(3),
    email: myzod
      .string()
      .withPredicate((value) => isEmail(value), "Email must be a valid email"),
    password: myzod
      .string()
      .min(8)
      .withPredicate(isStrongPassword, "Password is too weak"),
    confirmedPassword: myzod.string()
  })
  .withPredicate(
    (value) => value.password === value.confirmedPassword,
    "password and confirmed do not match"
  );

const ProfileSchema = myzod.pick(ProfileInputSchema, ["username", "email"]);

const WithCUID = myzod.object({
  id: myzod
    .string()
    .optional()
    .map((value) => cuid())
});

const ProfileSchemaWithCuid = ProfileSchema.and(WithCUID);

type Profile = Infer<typeof ProfileSchemaWithCuid>;

const result = ProfileSchemaWithCuid.try({
  username: "Parables",
  email: "parables95@gmail.com"
});

if (result instanceof myzod.ValidationError) {
  console.log("Invalid format");
} else {
  console.log("Result: ", result);
}

// console.log("Shape of ProfileSchemaWithCuid: ", ProfileSchemaWithCuid.shape());
```

**Comment by Parables** [comment]
checkout a live demo https://codesandbox.io/s/extend-myzod-schema-giwqf7

**Comment by Parables** [comment]
Hope it helps... let me know if there is anything else....

Thanks for accepting my PR once again... mean a lot to me

**Comment by Parables** [comment]
Sure no problem... I actually typed that code directly in the comments 🙃
