### ISSUE TITLE
Features request ( or bug ? )  - Add option notAllowEmptyArray

### ISSUE THREAD

**Issue by anhdd-kuro** [Code-Hex/graphql-codegen-typescript-validation-schema#254]
Just like notAllowEmptyString
notAllowEmptyArray: true will generate
```
z.array() => z.array().min(1)
```

or is this a bug ?
for example I have query like this

```
workDivisionIds: [String!]!
```

it should generate this right ?
```
workDivisionIds:  z.array(z.string()).min(1)
```

**Comment by Code-Hex** [comment]
@anhdd-kuro Thanks
I need to fix to be this

```
workDivisionIds:  z.array(z.string().min(1)).min(1)
```

**Comment by Code-Hex** [comment]
I'm sorry I close this issue for now. I'm wondering if this fix is really necessary. Will consider it again if someone posts a similar issue.
