### ISSUE TITLE
Dependency on graphql-constraint-directive

### ISSUE THREAD

**Issue by klippx** [Code-Hex/graphql-codegen-typescript-validation-schema#270]
First off, thanks for the lib! I find it very useful.

My feedback is that it is not well documented that we need to install `graphql-constraint-directive` for this lib to work. The docs just links to a spec that is not that nice to dig into as we don't have many clues what to look for or why we are in this spec file. I had to search for `constraint` in this repo and in the bit obscure `test.graphql` I find a link to https://github.com/confuser/graphql-constraint-directive

What is your take on if it is supposed to be a dependency to this package? I mean, I can't use `@constraint` which is half the point of this lib. I know you _can_ use this lib without `@constraint` but you know half the docs mention it so it is hard to see what is this lib and what is something else. 

What is your reasoning?

**Comment by Code-Hex** [comment]
Thanks for your feedback. However, I think you don't need to install `graphql-constraint-directive` to use this library.

Indeed, I wrote `@constraint` directive in the example code, but this code is written to prove works fine [`directives` config](https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema#directives).
