### ISSUE TITLE
doesn't work with client-preset

### ISSUE THREAD

**Issue by erwan-joly** [Code-Hex/graphql-codegen-typescript-validation-schema#303]
Hi, it seems like when using the client-preset the configuration is totally ignored.

```
import { CodegenConfig } from '@graphql-codegen/cli'

const config: CodegenConfig = {
    sort: false,
    schema: "file.graphql",
    documents: [
        "src/**/*.gql"
    ],
    ignoreNoDocuments: true,
    generates: {
        './src/graphql/': {
            preset: 'client',
            plugins: [
                "typescript-validation-schema",
            ],
            config: {
                 importFrom: './graphql',
                strictScalars: true,
                schema: 'zod',
            }
        }
    }
}

export default config
```
this code would result in the validation schema using yup (default configuration) instead of zod

I need an extra generation to get it to use the right configuration
```
import { CodegenConfig } from '@graphql-codegen/cli'

const config: CodegenConfig = {
    sort: false,
    schema: "file.graphql",
    documents: [
        "src/**/*.gql"
    ],
    ignoreNoDocuments: true,
    generates: {
        './src/graphql/validation.ts': {
            plugins: [
                "typescript-validation-schema",
            ],
            config: {
                importFrom: './graphql',
                strictScalars: true,
                schema: 'zod',
            }
        },
        './src/graphql/': {
            preset: 'client',
            plugins: [],
            config: {
            
            }
        }
    }
}

export default config
```

**Comment by Code-Hex** [comment]
@erwan-joly Thank you for pointing out the compatibility issue with the client-preset. I understand that the configuration is not being applied as expected when using it. Your input is valuable, and I appreciate your effort in sharing the workaround you've found.

To help other users who may encounter the same issue, it would be great if you could create a pull request to update the README with this information. I believe this would be a valuable addition to the documentation.

Thank you once again for your contribution, and I look forward to your continued support.

**Comment by erwan-joly** [comment]
Sure will try to do that as soon as I have some spare time :)

**Comment by erwan-joly** [comment]
https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/pull/361/files

**Comment by Code-Hex** [comment]
Close by https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/pull/361

**Comment by erwan-joly** [comment]
@Code-Hex is the workaround good enough ? seems a bit dirty
