### ISSUE TITLE
Schemas for mutation and query arguments

### ISSUE THREAD

**Issue by nightgrey** [Code-Hex/graphql-codegen-typescript-validation-schema#335]
First, thank you for the library! It has been extremely helpful :+1: 

My question is if it's possible to create schemas containing all arguments of a mutation / query, just like the `typescript` plugin does. I looked at the docs and source code but I can't find a way to do that.

### Issue

The plugin does generate schemas for specific arguments of a mutation or query, but it only does that if the argument has it's own type, but it doesn't generate a validation schema for all arguments. I'm not sure if that is an issue of my particular schema.

In case that was confusing, the example should provide more clarity.

### Examples

The examples only show the relevant parts.

**Schema**
```graphql
schema {
  query: Queries
  mutation: Mutations
}

type Mutations {
  asset: AssetNamespace!
}

type AssetNamespace {
  create(attachable: GlobalID!, title: String, file: File!, description: String, category: String, filename: String, public: Boolean, metadata: JsonBlob): AssetCreatePayload!
  
  // more mutations
}
```

**Output of the `typescript` plugin**
```ts
// Types for `Asset`, `AssetCreatePayload` (return type of `Asset.create`), etc.

export type AssetNamespaceCreateArgs = {
  attachable: Scalars['GlobalID'];
  category?: InputMaybe<Scalars['String']>;
  description?: InputMaybe<Scalars['String']>;
  file: Scalars['File'];
  filename?: InputMaybe<Scalars['String']>;
  metadata?: InputMaybe<Scalars['JsonBlob']>;
  public?: InputMaybe<Scalars['Boolean']>;
  title?: InputMaybe<Scalars['String']>;
};

// Types for the arguments of the other mutations
```

**Expectation**
```ts
// Schemas for `Asset`, `AssetCreatePayload` (return type of `Asset.create`), etc.

export const AssetNamespaceCreateArgsSchema = () => z.object({
  attachable: GlobalIDSchema(),
  title: z.string(),
  file: FileSchema(),
  // ....
});
```

**Current output**
```ts
// Schemas for `Asset`, `AssetCreatePayload` (return type of `Asset.create`), etc.

// No schema for `AssetNamespaceCreateArgs` (or other mutations / queries)
```

The plugin only generates schemas for distinct types (like `AssetCreatePayload`). 

Like for example, `examplify(searchParameters: ExampleSearchParameters!): ExamplePayload!`:
  * The `typescript` plugin would create a type for `ExampleNamespaceExamplifyArgs`
  * This plugin does not create `ExampleNamespaceExamplifyArgsSchema`, only a schema for `ExampleSearchParameters` itself.

---

So the question is: Is it possible to create schemas in this case?

I have looked in the source code of the plugin and tried to debug it myself, but I haven't gone too deep yet. The fact that `typescript` does generate those types seems like it should be possible too as they seem to use the same base / parser IIRC. 

If you can give me some pointers and if you're ok with that, I'd look into creating a PR for this myself! 

Thanks for your help!

**Comment by Code-Hex** [comment]
@nightgrey I apologize for the delayed response and thank you for your proposal.

First, I believe it is possible to generate schemas for the variables. However, I don't have an immediate solution in mind. If you already have some ideas or insights, I would greatly appreciate it if you could share them.

I'm in favor of addressing this issue.

Please let me know if you have any suggestions or insights, and I'll be happy to work with you on this. Thank you for your understanding and support!

**Comment by Code-Hex** [comment]
@nightgrey Please reopen if necessary 🙏
