### ISSUE TITLE
Support Superstruct

### ISSUE THREAD

**Issue by shellscape** [Code-Hex/graphql-codegen-typescript-validation-schema#367]
Please consider supporting superstruct https://docs.superstructjs.org/

It's smaller, more performant, and equally as capable as yup and zod. It just never got picked up by the tech influencers on Twitter so didn't get the popularity boost.

**Comment by Code-Hex** [comment]
@shellscape I checked superstruct GitHub repository but It looked like it hadn't been updated for a long time.

https://github.com/ianstormtaylor/superstruct

So I don't have the motivation to integrate it into this repository. However, contributions to this repository are welcome!

**Comment by shellscape** [comment]
Come again? It's stable. Stable packages don't need frequent updates, because they're stable.

**Comment by Code-Hex** [comment]
@shellscape I'm looking forward your contribution to add this!

**Comment by shellscape** [comment]
I greatly dislike passive aggressiveness, and don't feel it has any place in open source. rather than addressing and discussing the points you raised and my rebuttal, you've deflected. that's a bad signal. appreciate what you've put together here but I'll likely fork rather than contributing back given the responses in this issue.

**Comment by Code-Hex** [comment]
@shellscape I explained why I have no motivation to write code for this. However, I explained that it is acceptable for you to write and add to the repository instead, showing past links as example.
