### ISSUE TITLE
`@graphql-codegen/typescript` v4 breaks package

### ISSUE THREAD

**Issue by elijaholmos** [Code-Hex/graphql-codegen-typescript-validation-schema#373]
as you can see by the latest dep update 55277f1321f3feca7cf6cfd2a626efe49eaa2b8d, tests are failing due to breaking changes in the `@graphql-codegen/typescript` packages. I am also experiencing this in my local project; specifically, what was previously parsed as `z.string()` is now parsed as `definedNonNullAnySchema`:

![image](https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/assets/35435704/1b404414-a4ec-4f89-8f15-62dfe117c97f)

(v3 on the right, v4 on the left)

**Comment by valerii15298** [comment]
I have the same issue!!
Are there any workarounds?
That is basically first time I installed [graphql-codegen-typescript-validation-schema](https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema) and do not know to which versions which packages I should downgrade to make it work :(  ...

**Comment by Code-Hex** [comment]
@elijaholmos Thanks!
I think this problem is caused by this breaking change https://github.com/dotansimha/graphql-code-generator/pull/9375

I will fix this asap 🙏

**Comment by Code-Hex** [comment]
@elijaholmos @valerii15298 I just published the latest version for this.

Unfortunately, I couldn't maintain backward-compatible between `@graphql-codegen/typescript` v3 and v4. So you guys are required to do action to solve this problem :pray:

Please my release note: https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/releases/tag/v0.10.0
