### ISSUE TITLE
Add option "useTypeImports"

### ISSUE THREAD

**Issue by Toanzzz** [Code-Hex/graphql-codegen-typescript-validation-schema#376]
This is a feature request. Please add the option `useTypeImports` so we can use it in isomorphic application. 

It should me similar to this option: https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-operations#usetypeimports

**Comment by Code-Hex** [comment]
I just published the latest version as [v0.11.0](https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/releases/tag/v0.11.0)
