### ISSUE TITLE
Lost astNode in schema created by introspection query

### ISSUE THREAD

**Issue by Code-Hex** [Code-Hex/graphql-codegen-typescript-validation-schema#394]
The generation logic relied on the schema passed from graphql-codegen. If this was a schema generated based on introspection, the astNode information was lost, so it seems that it was not possible to determine whether each schema was an enum or a scalar.

This issue was reported here:

https://github.com/graphql/graphql-js/issues/1575

_Originally posted by @Code-Hex in https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/issues/386#issuecomment-1585481068_

**Comment by Code-Hex** [comment]
@maoosi I just published this fix now 🔥 
Thank you so much!
https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/releases/tag/v0.11.1

**Comment by maoosi** [comment]
@Code-Hex working great, thanks again for fixing it so fast!
