### ISSUE TITLE
typesPrefix option adds prefix to exported function

### ISSUE THREAD

**Issue by eyeruleall** [Code-Hex/graphql-codegen-typescript-validation-schema#44]
in the provided example, if we add the "`typesPrefix: I`" config option to the types generator config, we also have to add the same option to the schema generator config so it will add the prefix in the generated import {} statement. 

This works for importing, but unexpectedly causes the exported schema validation functions to also have the "I" prefix. 

Can you make it so adding the "typesPrefix" option only affects the types, and not the functions? Perhaps a "functionPrefix" option will be required, if that functionality is needed.

**Comment by Code-Hex** [comment]
@eyeruleall Thanks for your suggestion!
I agree with your opinion to add prefixes to any names.

> in the provided example, if we add the "typesPrefix: I" config option to the types generator config, we also have to add the same option to the schema generator config so it will add the prefix in the generated import {} statement.

But I don't know why you want to add prefixes to only import types? Why should not add to any validation schema?

**Comment by eyeruleall** [comment]
Because adding the "I" prefix is used to denote a block of code as an Interface, and Functions simply are not interfaces. 

More specifically, the option is called "typesPrefix," and one would expect it to only prefix types.

**Comment by Code-Hex** [comment]
OK. understand.

I want you to see this PR once.
https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/pull/45/files

As you can see, the base is a typescript plugin, so it could be generated in the past in this way.

So to maintain backward compatibility, I would add `trimPrefixValidationSchema: boolean`, `trimSuffixValidationSchema: boolean` instead. What do you say?

**Comment by Code-Hex** [comment]
@eyeruleall ping 🙏

**Comment by eyeruleall** [comment]
Sorry, I thought I replied. 

As written, your tests will pass but the import statement will be wrong, because there won't be any types with the "I" prefix from the typescript plugin.  

The idea is the typescript plugin has the option to add the "I" prefix to the types to identify a block of code as an Interface. The same option on your plugin should tell your plugin to generate the import statement with the "I" prefix. 

To prevent breaking changes, a "mappers" option could be the proper solution, like the base typescript plugin has.

**Comment by Code-Hex** [comment]
@eyeruleall 

Oh, it certainly differs if the option is not specified in the typescript plugin. However, I believe that it is not fundamental that only one of them has the option. Because it is obvious that it is not available.
>  there won't be any types with the "I" prefix from the typescript plugin.

Yes, so this plugin parses the config of that plugin based on the parsing function.
See https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/blob/337918e3fb9d12ffa31d9e02cb5e188a77d3a6cf/src/yup/index.ts#L18

> The idea is the typescript plugin has the option to add the "I" prefix to the types to identify a block of code as an Interface.

That's why I believe that the tests pass but the specification can never be wrong.

**Comment by Code-Hex** [comment]
@eyeruleall I'm sorry.
I don't have the motivation for this.

I'm closing this one, but your PR is most welcome!

**Comment by hinogi** [comment]
@Code-Hex Could we repone his since this is really annoying. You can archive this by using ambient types but if you want explicit types you run into this exact issue.
