### ISSUE TITLE
`.defined()` on input fields that has default value in schema

### ISSUE THREAD

**Issue by moander** [Code-Hex/graphql-codegen-typescript-validation-schema#511]
Version: `0.12.0`

The following query is accepted by the server, but `.validate()` fail with `displayName must be defined`. 

The expected behavior is to allow the undefined value and let the server take care of the default as defined in the SDL.

```gql
mutation {
  createLocation(input: {
    model: {
      description: ""
    }
  }) { id }
}
```

```gql
input LocationCreateInput {
  description: String
  displayName: String! = ""
}
```

```js
yup.object({
  description: yup.string().trim().defined().nullable().optional(), 
  displayName: yup.string().trim().defined().nonNullable(), // ERROR: displayName must be defined
})
```

**Comment by Code-Hex** [comment]
@moander I'm sorry, this library hasn't been supported yet for default values.
See: https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/issues/449

**Comment by moander** [comment]
Thank you @Code-Hex. This generator is really cool btw! 

My workaround for now is to use `.deepPartial()` on the schema to get rid of `.defined()` validation errors.
