### ISSUE TITLE
Support for non-input types?

### ISSUE THREAD

**Issue by markandrus** [Code-Hex/graphql-codegen-typescript-validation-schema#558]
I tried this out and, if I'm not mistaken, it only generates schemas (in my case, zod schemas) for input types. I would like to use this with non-input types as well (for example, to parse some JSON and ensure it adheres to the correct GraphQL type).

**Comment by MH4GF** [comment]
@markandrus @efstajas Wouldn't `withObjectType` solve this?

https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/blob/3a49a554b32d4c3121125c88a8e9f96c2e4b646f/README.md#withobjecttype

https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/blob/3a49a554b32d4c3121125c88a8e9f96c2e4b646f/tests/zod.spec.ts#L765-L808

**Comment by Code-Hex** [comment]
I close this issue because inactive. Please open again if you need anything else.
