### ISSUE TITLE
Support valibot (lightweight version of zod)

### ISSUE THREAD

**Issue by lopezjurip** [Code-Hex/graphql-codegen-typescript-validation-schema#577]
Consider Valibot over Zod: achieves lighter bundles & modularity, enhancing performance & flexibility.

https://bundlephobia.com/package/zod@3.22.4
It's 57KB gziped.

See: https://github.com/fabian-hiller/valibot

**Comment by Code-Hex** [comment]
@lopezjurip Hi!
I agree adding valibot support to this plugin.
Could you send me PR for this? Thanks!

**Comment by MH4GF** [comment]
@Code-Hex @lopezjurip 
I am a fan of graphql-codegen-typescript-validation-schema and valibot. I would like to submit a PR because I would like to use these two in a project I am working on! May I assign this issue to me?

**Comment by Code-Hex** [comment]
@MH4GF Sure! I'm looking forward your PR!

**Comment by MH4GF** [comment]
@Code-Hex Please let me confirm about the `definedNonNullAny` that is zod's temporary hack.

Surprisingly, valibot seems to compile the following code:

```ts
import * as v from 'valibot'

type A = {
  foo: any;
};

function AParser(): v.ObjectSchema<A> {
  return v.object({
    foo: v.any()
  });
}

type InferA = v.Input<ReturnType<typeof AParser>>;
// =>
// type InferA = {
//   foo: any;
// }
```

ref: https://github.com/colinhacks/zod/discussions/951

So, is the schema to be generated correct with the intention of `v.object({ foo: v.any() })` ?

**Comment by Code-Hex** [comment]
@MH4GF Thank you for your question.

In zod, I employed a hack to define a schema for the any type that excludes undefined and null. I hope to create something that aligns with this intention. 

Does this answer your question?

**Comment by Code-Hex** [comment]
@MH4GF Big Thanks!!

I just published valibot support version!
https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/releases/tag/v0.15.0
