### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by paales** [Code-Hex/graphql-codegen-typescript-validation-schema#596]
It has been a while since the last release and we'd like to use the latest version (especially https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/pull/529)

**Comment by Code-Hex** [comment]
@paales I published [v0.13.0](https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/tree/v0.13.0)!

**Comment by paales** [comment]
🎉 Thanks a lot @Code-Hex!
