### ISSUE TITLE
` ["min", "$1 - 1"]` generate unexpected `min("x - 1")`

### ISSUE THREAD

**Issue by azu** [Code-Hex/graphql-codegen-typescript-validation-schema#602]
For example, I want to implement `lessThan`(`<`) and `lessThanEqual`(`<=`) for string length.
There is no lessThanEqual function for string in zod, I think that it is necessary to use the `min` and `max` functions to implement this.

- https://zod.dev/?id=strings

However, graphql-codegen-typescript-validation-schema can not support operation like `$1 - 1`.

## Reproduce Example

- Repo: https://github.com/azu/graphql-codegen-typescript-validation-schema-plus-minus/tree/main

[Config](https://github.com/azu/graphql-codegen-typescript-validation-schema-plus-minus/blob/44da742292054214550817a267ac4fa32ee9c11c/codegen.ts#L22-L27):

```js
            config: {
                schema: "zod",
                strictScalars: true,
                scalars: {
                    ID: "string"
                },
                directives: {
                    constraint: {
                        min: ["min", "$1 - 1"],
                        max: ["max", "$1 + 1"]
                    }
                },
            },
```

[Schema](https://github.com/azu/graphql-codegen-typescript-validation-schema-plus-minus/blob/44da742292054214550817a267ac4fa32ee9c11c/api/api.graphqls):

```graphql
input ExampleInput {
  email: String!
  message: String! @constraint(min: 1, max: 1000)
}
```

[Actual Output](https://github.com/azu/graphql-codegen-typescript-validation-schema-plus-minus/blob/44da742292054214550817a267ac4fa32ee9c11c/codegen.ts#L22-L27)

```js
export function ExampleInputSchema(): z.ZodObject<Properties<ExampleInput>> {
  return z.object({
    email: z.string(),
    message: z.string().min("1 - 1").max("1000 + 1")
  })
}
```

Expected Output:

```diff
export function ExampleInputSchema(): z.ZodObject<Properties<ExampleInput>> {
  return z.object({
    email: z.string(),
-    message: z.string().min("1 - 1").max("1000 + 1")
+    message: z.string().min(1 - 1).max(1000 + 1)
  })
}
```

Unexpected quote is inserted.

## Context

In the comment, it seems that `["min", "$1 - 1"]` is supported, so I don't know if this is a bug or a function that does not support.

https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/blob/ba0a27de2550ae478667874b9439d977d2292960/src/config.ts#L247C20-L248

If this syntax is not supported, we can just close this issue.

**Comment by Code-Hex** [comment]
@azu Thanks for your report!
I fixed this issue in [v0.13.0](https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/tree/v0.13.0)!

**Comment by azu** [comment]
@Code-Hex Thanks!

**Comment by azu** [comment]
https://github.com/azu/graphql-codegen-typescript-validation-schema-plus-minus/commit/17cb37db8e18bbad108d8bd68f905cb5ac2899e1
﻿I confirmed that it has been fixed.
