### ISSUE TITLE
How to handle enum on directive arguments?

### ISSUE THREAD

**Issue by azu** [Code-Hex/graphql-codegen-typescript-validation-schema#611]
I want to handle Enum value on directive arguments.

For example, `@validateString(format: EMAIL)` use enum value on arguemnts.

```graphql
"""
@validateString specifies constraints on an String/ID field or argument.
"""
directive @validateString(
    """
    'format' specifies that the value must match the specified format.
    """
    format: StringFormat
) on INPUT_FIELD_DEFINITION | ARGUMENT_DEFINITION

"""
StringFormat represents the format of a string.
""" # eslint-disable-next-line @graphql-eslint/no-unreachable-types
enum StringFormat {
    """
    EMAIL represents the format of an email address.
    """
    EMAIL

    """
    IP represents the format of an IP address.
    """
    IP
}

# All validation directives
input Example {
    # string format directives
    email: String! @validateString(format: EMAIL)
    ip: String! @validateString(format: IP)
}
```

[graphql-codegen-typescript-validation-schema](https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema) always ignore the enum value, I think.

How to handle enum on directive arguments?

## Example 

- Repo: https://github.com/azu/graphql-codegen-typescript-validation-schema-enum-as-param

I try to write following config, but it is just ignored.

```ts
        "src/graphql.ts": {
            plugins: [
                "typescript",
                "typescript-validation-schema"
            ],
            config: {
                schema: "zod",
                strictScalars: true,
                scalars: {
                    ID: "string"
                },
                scalarSchemas: {

                },
                enumsAsTypes: true,
                directives: {
                    validateString: {
                        format: {
                            EMAIL: "email",
                            IP: "ip"
                        }
                    }
                },
            },
        }
```

It is ideal to be able to convert to the next by setting something.

```graphql
@validateString(format: EMAIL)
```

→

```ts
z.string().email()
```

**Comment by Code-Hex** [comment]
@azu Thanks for asking question to me!

I apologize for not mentioning this in the documentation. As an implementation, the directive argument currently supports only pure String.

I think it is probably better to accept any type that can be converted to a String. I will add this feature.

**Comment by Code-Hex** [comment]
In addition, this [example](https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema?tab=readme-ov-file#directives) (`email`: `email`) meant `[validation-schema-name]: directive-args-string`. 

```
format:
  email: email
```

**Comment by Code-Hex** [comment]
@azu I supported enum in [0.14.1](https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/releases/tag/v0.14.1). Could you try this one? Thanks!

**Comment by azu** [comment]
@Code-Hex Thanks!

I've confirmed to work Enum.
https://github.com/azu/graphql-codegen-typescript-validation-schema-enum-as-param/commit/e3d1d707e38baeb775cfb1a44bb691ae258d594a
