### ISSUE TITLE
useTypeImports option and consistent-type-imports

### ISSUE THREAD

**Issue by socnacom** [Code-Hex/graphql-codegen-typescript-validation-schema#614]
When using enums, if `useTypeImports` is set to `true`, then generated code won't work since enums cannot be used as values. Example of generated code :

```
export const AddressTypeEnumSchema = yup.string<AddressTypeEnum>().oneOf([AddressTypeEnum.Billing, AddressTypeEnum.Delivery, AddressTypeEnum.FolderOrMission, AddressTypeEnum.HeadOffice, AddressTypeEnum.ResearchUnit, AddressTypeEnum.Residence, AddressTypeEnum.SecondaryOffice]).defined();
```

Alternatively, If `useTypeImports` is set to `false`, then generated `import` instruction isn't perfectly valid : 
```
Imports "XXX", "YYY" are only used as type.eslint[@typescript-eslint/consistent-type-imports](https://typescript-eslint.io/rules/consistent-type-imports)
```

**Comment by Code-Hex** [comment]
@socnacom Hi!
Could you give me a minimal reproduction repository such as https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/issues/602 ?

Thanks!

**Comment by Code-Hex** [comment]
No reply. close
