### ISSUE TITLE
Yup schema won't add 'nullable' to optional fields.

### ISSUE THREAD

**Issue by adamwdennis** [Code-Hex/graphql-codegen-typescript-validation-schema#64]
When I run the generator, my Yup schema does not add `.nullish()` to any optional fields.

### `my-type.ts`
```ts
@InputType
export class MyTypeInput {

  @Field(() => String)
  @IsString()
  @IsDefined()
  name!: string;

  @Field(() => ID, { nullable: true })
  @IsString()
  @IsOptional()
  imageId?: string;
}
```

### `schema.graphql`
```gql
input MyTypeInput {
  name: String!
  imageId: ID
}
```

### `generated-operations.ts`
```ts
export type MyTypeInput = {
  imageId?: InputMaybe<Scalars['ID']>;
  name: Scalars['String'];
}
```
----
### `generated-validation-schema.ts`
```ts
export function MyTypeInputSchema(): yup.SchemaOf<MyTypeInput> {
  return yup.object({
    imageId: yup.string().nullable(),  // <----- this `nullable` is missing in the actual, below
    name: yup.string().defined()
  })
}
```

### `generated-validation-schema.ts`
```ts
export function MyTypeInputSchema(): yup.SchemaOf<MyTypeInput> {
  return yup.object({
    imageId: yup.string(),
    name: yup.string().defined()
  })
}
```

**Comment by adamwdennis** [comment]
Hi @Code-Hex -- thanks for the quick response here... I've updated the description, per your request, with a  `schema.graphql` section.

**Comment by Code-Hex** [comment]
@adamwdennis Thanks. I confirmed the problem.

https://codesandbox.io/s/yup-forked-z4fgyw?file=/src/index.js

I will fix this

**Comment by Code-Hex** [comment]
I remember why this is happening.
The type currently used (yup.SchamaOf) does not support nullable arrays.

https://github.com/jquense/yup/issues/1440#issue-966163167

If this fix is made now, primitives will not have the problem, but arrays will not compile.
It is now implemented as a workaround.

What do you think, should we wait until the 1.0.0 release?

**Comment by Code-Hex** [comment]
Note (my question issue for next): https://github.com/jquense/yup/issues/1658

**Comment by adamwdennis** [comment]
Thanks for the above.  Is `zod` an immediate, working alternative?  I'm using the `graphql-codegen-typescript-validation-schema` with yup for Formik validation. I've found a plugin that can help me get a `zod` schema working with Formik, but when I use generate using `schema: zup`, I get errors within fields which are arrays of required types.

**Comment by Code-Hex** [comment]
@adamwdennis Yes, I think so. zod is good one.
> Is zod an immediate, working alternative

I'm sorry this plugin does not support for zup.
see https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema#config-api-reference

> I use generate using schema: zup, I get errors within fields which are arrays of required types.

**Comment by qwexvf** [comment]
@Code-Hex Hi. Thanks for the amazing library btw! Does this still a progressing issue?
I'm trying to achieve the result below ↓

I currently have a input like below. (forgive me for using a language-specific implementation input object)
```elixir
  input_object :update_input do
    field(:id, non_null(:id))
    field(:email, :string)
    field(:name, :string)
  end
``` 

This is what codegen generated for me which is correct to my input defined on the server.
```ts
export type UpdateInput = {
    id: Scalars["ID"] # ID is required
    name?: InputMaybe<Scalars["String"]> # this is nullable
    email?: InputMaybe<Scalars["String"]> # this is nullable
}
```

This is what I got from your codegen.
field `email` and `name` are required whereas the generated types have `optional` and `nullable` options.
```ts
export function UpdateInputSchema(): yup.SchemaOf<UpdateInput> {
    return yup.object({
        id: yup.string().defined(),
        email: yup.string(),
        name: yup.string(),
    })
}
```

These are the results I expected. I might not even need the `optional` field but can I somehow get the `nullable()` ?
```ts
return yup.object({
  id: yup.string().defined(),
  email: yup.string().nullable(),
   name: yup.string().nullable(),
})
```

could you help me achieve this?
Thanks!

**Comment by Code-Hex** [comment]
@qwexvf Hi 👋 

I think the code that is you want will be occurred compilation error by `yup.SchemaOf<UpdateInput>`

```ts
return yup.object({
  id: yup.string().defined(),
  email: yup.string().nullable(),
   name: yup.string().nullable(),
})
```

By the way, Could you share me your GraphQL schema (only UpdateInput)?

**Comment by Code-Hex** [comment]
I think this problem has been resolved at https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/pull/351
