### ISSUE TITLE
Zod Schema: How to add custom error message (i18n)

### ISSUE THREAD

**Issue by knoefel** [Code-Hex/graphql-codegen-typescript-validation-schema#86]
So, this is more like a question/discussion rather than an actual issue:

Is there a way to customise the error message for the generated zod schemas? For example, i want to set a required string message to support i18n messages.

Maybe this is something that's possible with zod already but i couldn't find any infos about it.

Thanks in advance and also for the great work with this plugin!!

**Comment by Code-Hex** [comment]
@knoefel Thank you for using this plugin and your comment!!

I'm sorry, I don't have an idea to support i18n message on zod. But I found [this issue](https://github.com/colinhacks/zod/issues/97) that is discussing about custom error handling way as you said.

Please ask that in the issue. Thank you.
